Repository sandpiper-toolchain/sandplover, pull requests merged in 2023-02, with the labels that each got.

#130 Create sections into objects other than cube (mask, plan, arrays)
  deltametrics/_version.py
  deltametrics/cube.py
  deltametrics/mask.py
  deltametrics/plan.py
  deltametrics/plot.py
  deltametrics/section.py
  docs/source/guides/examples/computations/shoreline_roughness_perfect_direct.rst
  docs/source/guides/examples/create_from/sections_into_arbitrary.rst
  docs/source/guides/examples/index.rst
  docs/source/guides/subject_guides/section.rst
  tests/test_section.py
Labels: enhancement, section

#131 draft version of Stuart Pearson's vintage colormap
  deltametrics/plot.py
  docs/source/reference/plot/index.rst
  tests/test_plot.py
Labels: plotting

#133 GeometricMask improvements
  deltametrics/mask.py
  tests/test_mask.py
Labels: enhancement, masks

#134 fix wetmask from planform bug
  deltametrics/plan.py
  tests/test_mask.py
Labels: bug

#135 compute_land_area
  deltametrics/plan.py
  docs/source/guides/examples/computations/shoreline_roughness_perfect_direct.rst
  docs/source/reference/plan/index.rst
  tests/test_plan.py
Labels: planform

#136 Stratigraphy metrics
  deltametrics/strat.py
  docs/source/guides/examples/computations/computing_sedimentograph.rst
  docs/source/guides/examples/index.rst
  docs/source/reference/strat/index.rst
  tests/test_strat.py
Labels: enhancement, stratigraphy
